// GENERATED by scripts/extract-test-hands.mjs from src/lib/scoring.test.ts -
// don't edit by hand; rerun the script after changing the scoring tests.
//
// The hidden "Test hands" sheet's list (tap the MJWaits logo 5 times): each
// winning hand the scoring tests score, with the situation that test sets.

import type { GameContext } from "./scoring";

export interface TestHand {
  /** The describe() block the test sits in. */
  group: string;
  /** The test's own name. */
  name: string;
  /** Scoring notation - "(123m)" a declared meld, the rest concealed. */
  hand: string;
  /** The test's ctx() overrides, on top of the defaults. */
  ctx: Partial<GameContext>;
}

/** scoring.test.ts's ctx() defaults - every entry's ctx is on top of these. */
export const TEST_HAND_BASE_CONTEXT: GameContext = {
  seatWind: 1,
  roundWind: 1,
  selfDraw: false,
  winningTile: null,
  riichi: "none",
  instantWin: false,
  eatRiichi: false,
  earlyWin: "none",
  multiWin: "none",
  heavenlyWin: "none",
  lastTileWin: "none",
  flowerDraw: 0,
  kongDraw: 0,
  robKong: 0,
  dealerStreak: 0,
  manualVisibleTripleWin: false,
  manualVisibleExhaustedMultiWait: false,
};

export const TEST_HANDS: TestHand[] = [
  {
    "group": "scoreHand",
    "name": "scores 無花 when the hand has no bonus tiles",
    "hand": "(111z)123456789m234t22b",
    "ctx": {}
  },
  {
    "group": "scoreHand",
    "name": "picks the max-tai decomposition when a hand is genuinely ambiguous",
    "hand": "111222333m111z456b22t",
    "ctx": {}
  },
  {
    "group": "底 (base tai)",
    "name": "applies unconditionally to every completed hand",
    "hand": "123456789m111z234t22b",
    "ctx": {}
  },
  {
    "group": "底 (base tai)",
    "name": "applies unconditionally to every completed hand",
    "hand": "123m123m123t456b111z22z",
    "ctx": {}
  },
  {
    "group": "槓 (kong)",
    "name": "stacks 2 tai for a concealed kong",
    "hand": "[1111z]123456789m234t22b",
    "ctx": {}
  },
  {
    "group": "槓 (kong)",
    "name": "stacks 2 tai for an exposed kong too",
    "hand": "(1111z)123456789m234t22b",
    "ctx": {}
  },
  {
    "group": "槓 (kong)",
    "name": "stacks across multiple kongs regardless of concealed/exposed mix",
    "hand": "[1111z][2222z]123456789m22b",
    "ctx": {}
  },
  {
    "group": "爛位風/正位風 (wind meld(s) vs. seat wind)",
    "name": "scores neither with no wind meld at all",
    "hand": "111222333m444555t22b",
    "ctx": {}
  },
  {
    "group": "小三風/大三風 and exclusion of the single-wind patterns",
    "name": "scores 小三風 for 2 wind melds + the spare wind as pair, excluding the singles",
    "hand": "(111z)(222z)123456789m33z",
    "ctx": {
      "seatWind": 1,
      "roundWind": 1
    }
  },
  {
    "group": "小三風/大三風 and exclusion of the single-wind patterns",
    "name": "does not score 小三風 when the pair isn't the spare wind",
    "hand": "(111z)(222z)123456789m22b",
    "ctx": {}
  },
  {
    "group": "小三風/大三風 and exclusion of the single-wind patterns",
    "name": "scores 大三風 for 3 wind melds, excluding 小三風 and the singles",
    "hand": "(111z)(222z)(333z)123456t22b",
    "ctx": {
      "seatWind": 1,
      "roundWind": 1
    }
  },
  {
    "group": "小三風/大三風 and exclusion of the single-wind patterns",
    "name": "breaks 大三風/小三風 down sorted 1z/2z/3z(/4z), not declared-first-then-concealed order",
    "hand": "(333z)111z222z456m789t22b",
    "ctx": {}
  },
  {
    "group": "小三風/大三風 and exclusion of the single-wind patterns",
    "name": "breaks 大三風/小三風 down sorted 1z/2z/3z(/4z), not declared-first-then-concealed order",
    "hand": "(333z)111z44z456m789t123b",
    "ctx": {}
  },
  {
    "group": "小四喜/大四喜 and exclusion of the smaller wind patterns",
    "name": "scores 小四喜 for 3 wind melds + the 4th as pair, excluding everything smaller",
    "hand": "(111z)(222z)(333z)123456t44z",
    "ctx": {
      "seatWind": 1,
      "roundWind": 1
    }
  },
  {
    "group": "小四喜/大四喜 and exclusion of the smaller wind patterns",
    "name": "scores 大四喜 for all 4 wind melds, excluding everything smaller",
    "hand": "(111z)(222z)(333z)(444z)123b22t",
    "ctx": {
      "seatWind": 1,
      "roundWind": 1
    }
  },
  {
    "group": "小四喜/大四喜 and exclusion of the smaller wind patterns",
    "name": "breaks 大四喜/小四喜 down sorted 1z/2z/3z/4z, not declared-first-then-concealed order",
    "hand": "(333z)111z222z444z678m55m",
    "ctx": {}
  },
  {
    "group": "小四喜/大四喜 and exclusion of the smaller wind patterns",
    "name": "breaks 大四喜/小四喜 down sorted 1z/2z/3z/4z, not declared-first-then-concealed order",
    "hand": "(333z)111z222z44z456m789t",
    "ctx": {}
  },
  {
    "group": "三元牌/小三元/大三元 and their exclusions",
    "name": "stacks 三元牌 2 tai per dragon meld when the pair isn't the spare dragon",
    "hand": "(555z)(666z)123456789m22b",
    "ctx": {}
  },
  {
    "group": "三元牌/小三元/大三元 and their exclusions",
    "name": "scores 小三元 for 2 dragon melds + the spare dragon as pair, excluding 三元牌",
    "hand": "(555z)(666z)123456789m77z",
    "ctx": {}
  },
  {
    "group": "三元牌/小三元/大三元 and their exclusions",
    "name": "scores 大三元 for all 3 dragon melds, excluding 三元牌 and 小三元",
    "hand": "(555z)(666z)(777z)123456t22b",
    "ctx": {}
  },
  {
    "group": "三元牌/小三元/大三元 and their exclusions",
    "name": "breaks 大三元/小三元 down sorted 5z/6z/7z, not declared-first-then-concealed order",
    "hand": "(777z)555z666z123456t22b",
    "ctx": {}
  },
  {
    "group": "三元牌/小三元/大三元 and their exclusions",
    "name": "breaks 大三元/小三元 down sorted 5z/6z/7z, not declared-first-then-concealed order",
    "hand": "(777z)555z66z123456t123b",
    "ctx": {}
  },
  {
    "group": "字一色 (all-honors)",
    "name": "scores when every tile in the hand is an honor, excluding 混老頭 (which needs at least one terminal)",
    "hand": "(111z)(222z)(333z)(444z)(555z)66z",
    "ctx": {}
  },
  {
    "group": "平胡 (all-runs) and 無字花大平胡",
    "name": "doesn't score 無字花大平胡 when no-honors-no-flowers holds but a triplet is forced",
    "hand": "111m22m456t789t234b678b",
    "ctx": {}
  },
  {
    "group": "缺一門 (missing-one-suit)",
    "name": "scores when exactly 2 of the 3 numbered suits are used and there are no honors",
    "hand": "123456789m234t678t55t",
    "ctx": {}
  },
  {
    "group": "缺一門 (missing-one-suit)",
    "name": "doesn't score when all 3 numbered suits are used",
    "hand": "123456789m234t678t22b",
    "ctx": {}
  },
  {
    "group": "缺一門 (missing-one-suit)",
    "name": "doesn't score when the pair is honors, even with exactly 2 suits used",
    "hand": "123123678678m777b11z",
    "ctx": {}
  },
  {
    "group": "缺一門 (missing-one-suit)",
    "name": "doesn't score when an honor meld is present, even with a non-honor pair and exactly 2 suits used",
    "hand": "222b444b777b66b444m111z",
    "ctx": {}
  },
  {
    "group": "缺五 (no-fives)",
    "name": "scores when the hand has no honors and no rank-5 tile",
    "hand": "123m678m123t789t678b44b",
    "ctx": {}
  },
  {
    "group": "小五門齊/大五門齊",
    "name": "scores 小五門齊 when all 5 categories are present but not all fully melded",
    "hand": "123m456t789t678b111z55z",
    "ctx": {}
  },
  {
    "group": "小五門齊/大五門齊",
    "name": "scores 大五門齊 when all 5 categories each have a dedicated meld",
    "hand": "123m456t678b111z555z99m",
    "ctx": {}
  },
  {
    "group": "大於五/小於五",
    "name": "scores 大於五 for an all-6-to-9 hand, excluding 缺五",
    "hand": "678m789m678t789t678b99b",
    "ctx": {}
  },
  {
    "group": "大於五/小於五",
    "name": "scores 小於五 for an all-1-to-4 hand, excluding 缺五",
    "hand": "123m234m123t234t123b44b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 斷么 (all-simples)",
    "name": "scores when every tile is ranked 2-8",
    "hand": "234m567m234t567t234b66b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 對對胡/坎坎胡 and the 暗刻 chain",
    "name": "對對胡 scores for all-triplet/kong hands, not for hands with a run",
    "hand": "111m333m555m777t99t999b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 對對胡/坎坎胡 and the 暗刻 chain",
    "name": "a kong disqualifies 坎坎胡 even with self-draw, but still counts toward 五暗刻",
    "hand": "[1111m]999m456t789t234b22b",
    "ctx": {
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 對對胡/坎坎胡 and the 暗刻 chain",
    "name": "counts exactly 2/3/4 concealed triplets at the right tiers",
    "hand": "111m333m456t789t234b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 對對胡/坎坎胡 and the 暗刻 chain",
    "name": "counts exactly 2/3/4 concealed triplets at the right tiers",
    "hand": "111m333m555m456t789b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 對對胡/坎坎胡 and the 暗刻 chain",
    "name": "counts exactly 2/3/4 concealed triplets at the right tiers",
    "hand": "111m333m555m777m456t22t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 對對胡/坎坎胡 and the 暗刻 chain",
    "name": "a triplet completed by a claimed (non-self-draw) winning tile doesn't count as hidden",
    "hand": "111m333m456t789t234b22b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      },
      "selfDraw": false
    }
  },
  {
    "group": "PATTERNS: 五槓子",
    "name": "scores 240 for 5 kongs, excluding 槓/四暗刻/五暗刻 but not 對對胡",
    "hand": "[1111m][2222m][3333m][4444m][5555t]66t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明清龍/暗清龍 (pure straight, with duplicate instances)",
    "name": "counts 2x 明清龍 when a whole 123-456-789-789 group is all declared",
    "hand": "(123m)(456m)(789m)(789m)234t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明清龍/暗清龍 (pure straight, with duplicate instances)",
    "name": "splits into 1 暗清龍 + 1 明清龍 when only one duplicate segment is declared",
    "hand": "(789m)123456789m234t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明清龍/暗清龍 (pure straight, with duplicate instances)",
    "name": "counts all 4 combinations when both the low and high segments are duplicated (123m123m456m789m789m) - not just 2 paired by index",
    "hand": "123m123m456m789m789m55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明清龍/暗清龍 (pure straight, with duplicate instances)",
    "name": "only opens the ONE specific 789m copy the claimed tile actually completed, leaving the other 789m copy (and both 123m+456m+789m readings through it) genuinely hidden",
    "hand": "123m456m789m789m234t22z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 9
      }
    }
  },
  {
    "group": "PATTERNS: 明雜龍/暗雜龍 (mixed straight across suits)",
    "name": "scores 暗雜龍 for a fully concealed 123m+456t+789b",
    "hand": "123m234m456t567t789b99b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明雜龍/暗雜龍 (mixed straight across suits)",
    "name": "scores 明雜龍 once one of the three segments is declared",
    "hand": "(123m)234m456t567t789b99b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 老少上/老少碰",
    "name": "counts all 4 combinations when both 123 and 789 are duplicated (2x2), not just 2 paired by index",
    "hand": "123m123m789m789m456t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 老少上/老少碰",
    "name": "doesn't score 老少上 for a suit that also has the 456 segment (that's 清龍 instead)",
    "hand": "123456789m234t567t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 老少上/老少碰",
    "name": "scores 老少碰 for a rank-1 + rank-9 triplet in one suit",
    "hand": "111m999m456t789t234b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 老少上/老少碰",
    "name": "a kong of rank 1 or 9 counts toward 老少碰 too",
    "hand": "[1111m]999m456t789t234b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶X (common rank across every non-honor meld)",
    "name": "scores when every non-honor meld shares rank 3 (the pair is exempt)",
    "hand": "123234345m333b123t11z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶X (common rank across every non-honor meld)",
    "name": "an honor meld is exempt from needing the common rank too",
    "hand": "123234345m333b111z33t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶X (common rank across every non-honor meld)",
    "name": "the pair must also match the shared rank, unless the pair itself is honors",
    "hand": "123234345m333b111z22t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶X (common rank across every non-honor meld)",
    "name": "the pair must also match the shared rank, unless the pair itself is honors",
    "hand": "123234345m333b111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶XY (common rank pair across every non-honor meld)",
    "name": "scores when every non-honor meld shares ranks 2 and 3, excluding 混帶X",
    "hand": "123234m123t123b11122z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶XY (common rank pair across every non-honor meld)",
    "name": "doesn't score when the pair is non-honor, even if its rank matches one of the two shared ranks",
    "hand": "123m234m123t123b111z22m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶XYZ (common rank triple across every non-honor meld)",
    "name": "scores when every non-honor meld shares ranks 1, 2, and 3, excluding 混帶XY",
    "hand": "123m123b123m11122233z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶XYZ (common rank triple across every non-honor meld)",
    "name": "still counts with only a single non-honor meld - a run trivially shares its own 3 ranks",
    "hand": "111z222z555z666z123m33z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶XYZ (common rank triple across every non-honor meld)",
    "name": "a lone triplet/kong never qualifies (only 1 distinct rank, never 3)",
    "hand": "111z222z555z666z333t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶XYZ (common rank triple across every non-honor meld)",
    "name": "doesn't score when the pair is non-honor, even if its rank matches one of the three shared ranks",
    "hand": "123m123b123m123t111z11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 全帶X (common rank across every meld and the pair, no honors)",
    "name": "scores when every meld and the pair all share rank 2 - 222234t splits as triplet+run, not a kong - excluding 混帶X",
    "hand": "123234m222234t123b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么 (honor presence + terminal in every non-honor meld, and the pair)",
    "name": "scores with an honor meld, a terminal in every non-honor meld, and a terminal pair",
    "hand": "123m789m123t111z789b11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么 (honor presence + terminal in every non-honor meld, and the pair)",
    "name": "scores just as well with an honor pair instead of a terminal one - honor presence can come from the pair alone, no honor meld needed",
    "hand": "123m789m123t789b999t22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么 (honor presence + terminal in every non-honor meld, and the pair)",
    "name": "doesn't score once any non-honor meld lacks a terminal",
    "hand": "123m456m123t111z789b11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么 (honor presence + terminal in every non-honor meld, and the pair)",
    "name": "doesn't score without any honor presence, even if every meld has a terminal",
    "hand": "123m789m123t789t789b11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么 (honor presence + terminal in every non-honor meld, and the pair)",
    "name": "doesn't score when the pair itself is neither a terminal nor honors, even with an honor meld elsewhere",
    "hand": "123m789m123t111z789b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 全帶么 (no honors, terminal in every meld and the pair)",
    "name": "scores when every meld and the pair contain a terminal, no honors anywhere",
    "hand": "123m789m123t789t123b99b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 全帶么 (no honors, terminal in every meld and the pair)",
    "name": "doesn't score once the pair itself lacks a terminal",
    "hand": "123m789m123t789t123b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 全帶么 (no honors, terminal in every meld and the pair)",
    "name": "excludes 缺五 - a terminal in every meld and the pair structurally guarantees no fives anywhere",
    "hand": "123m789m123t789b999t11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混老頭/清老頭 (all triplets/kongs, terminals and/or honors)",
    "name": "scores 混老頭 for all-triplet terminal+honor tiles, excluding the 帶么 patterns",
    "hand": "111m999m111z555z999t11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混老頭/清老頭 (all triplets/kongs, terminals and/or honors)",
    "name": "scores 清老頭 for all-triplet terminal-only tiles (no honors), excluding the 帶么 patterns and 混老頭",
    "hand": "111m999m111t999t999b11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸一 (triplet + run using all 4 copies of a rank)",
    "name": "scores 暗四歸一 for a fully concealed triplet+run split",
    "hand": "123m222m777m999b777t11z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸一 (triplet + run using all 4 copies of a rank)",
    "name": "scores 明四歸一 once the triplet half is declared",
    "hand": "(222m)123m777m999b777t11z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸二 (pair + 2 runs using all 4 copies of a rank)",
    "name": "scores 暗四歸二 for a fully concealed pair+2-runs split",
    "hand": "123m234m22m789t789b111z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸四 (4 runs using all 4 copies of a rank)",
    "name": "scores 暗四歸四 for 4 concealed runs all containing the same rank",
    "hand": "234m234m345m456m777t99b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸四 (4 runs using all 4 copies of a rank)",
    "name": "stacks 3 instances for 4 identical runs (123m x4) - one per rank (1m/2m/3m), not capped at 1",
    "hand": "123m123m123m123m456t55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗般高 (identical sequences)",
    "name": "scores 暗般高 once for a single pair of identical concealed runs",
    "hand": "123m123m456t789t111z22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗般高 (identical sequences)",
    "name": "scores 明般高 once one of the two identical runs is declared",
    "hand": "(123m)123m456t789t111z22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗小雙般高 (pair at one end of twin sequences)",
    "name": "scores 暗小雙般高 for 22334455m, excluding 般高",
    "hand": "22334455m111z789t789b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗小雙般高 (pair at one end of twin sequences)",
    "name": "doesn't fire at all when one of the twin runs is a declared meld - no genuine dual reading exists",
    "hand": "(345m)22345m111z789t789b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      },
      "selfDraw": false
    }
  },
  {
    "group": "PATTERNS: 明/暗小雙般高 (pair at one end of twin sequences)",
    "name": "counts as 明, not 暗, when the claimed winning tile completed the pair, not either run",
    "hand": "22334455m111z789t789b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      },
      "selfDraw": false
    }
  },
  {
    "group": "PATTERNS: 明/暗小雙般高 (pair at one end of twin sequences)",
    "name": "still counts as 暗 when that same pair-completing tile was self-drawn",
    "hand": "22334455m111z789t789b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      },
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 明/暗一色三同順 (3 identical sequences)",
    "name": "scores 暗一色三同順 for 3 concealed identical runs, excluding 般高",
    "hand": "123m123m123m456t789b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗一色四同順 (4 identical sequences)",
    "name": "scores 暗一色四同順 for 4 concealed identical runs, excluding 般高 and 三同順",
    "hand": "123m123m123m123m456b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗真雙般高 (2 separate identical-sequence pairs)",
    "name": "scores 暗真雙般高 for 123123m + 678678t, excluding 般高",
    "hand": "123m123m678t678t456b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗單色步步高 (3 ascending sequences, gap 1)",
    "name": "scores 暗單色步步高 once for 123m234m345m",
    "hand": "123m234m345m789t111z22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗單色步步高 (3 ascending sequences, gap 1)",
    "name": "counts twice for 123m234m345m345m (the duplicate 345m reuses 123m/234m)",
    "hand": "123m234m345m345m111z22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗單色二步高 (3 sequences, gap 2)",
    "name": "scores 暗單色二步高 once for 123m345m567m",
    "hand": "123m345m567m111z789t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗單色二步高 (3 sequences, gap 2)",
    "name": "counts twice for 123m345m567m567m (the duplicate 567m reuses 123m/345m)",
    "hand": "123m345m567m567m111z22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 二連刻 (2 consecutive triplets/kongs)",
    "name": "scores once for 222m333m",
    "hand": "222m333m789t456b789b11z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 二連刻 (2 consecutive triplets/kongs)",
    "name": "still counts with a kong involved (222m3333m)",
    "hand": "222m[3333m]456t789t789b22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三連刻/大三連刻",
    "name": "scores 小三連刻 for 22m333m444m (pair at the low end), excluding 二連刻",
    "hand": "333m444m789t456b789b22m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三連刻/大三連刻",
    "name": "scores 大三連刻 for 333m444m555m (no pair involved), excluding 二連刻",
    "hand": "333m444m555m789t111z22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三連刻/大三連刻",
    "name": "stacks 3 instances of 大三連刻 for 111m222m333m444m555m - overlapping windows [1,2,3]/[2,3,4]/[3,4,5]",
    "hand": "111m222m333m444m555m22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三連刻/大三連刻",
    "name": "stacks 3 instances of 小三連刻 when the pair sits in the middle of 4 flanking triplets (1m/2m/4m/5m around a 3m pair)",
    "hand": "111m222m444m555m33m789t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三連刻/大三連刻",
    "name": "still counts a genuinely separate 二連刻 pair that 大三連刻 doesn't claim - 111m222m333m (big window) + 555t666t (unrelated pair, different suit)",
    "hand": "111m222m333m555t666t22b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三連刻/大三連刻",
    "name": "breaks 小三連刻 down sorted by rank, not pair-always-first",
    "hand": "333m555m789t456b789b44m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混一色/清一色",
    "name": "scores 混一色 for a hand using only one numbered suit plus honors",
    "hand": "123456789m111z555z22m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混一色/清一色",
    "name": "scores 清一色 for a hand using only one numbered suit and no honors, excluding 混一色",
    "hand": "123456789m123m456m22m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 相逢 once for 234m+234t (2 suits, same run)",
    "hand": "234m234t567b789b111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 相逢 twice for 123m123m123t - the single 123t is shared (not consumed) by both 123m copies, same non-exclusive-pairing principle as combineSegments",
    "hand": "123m123m123t456b789b11z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "still counts a genuinely separate 相逢 pair that 暗三相逢 doesn't claim - 123m123t123b (rank-1 triple) + 789m789t (unrelated pair, different rank)",
    "hand": "123m789m123t789t123b55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 明三相逢 for 567m+567t+567b with one run exposed, excluding 相逢",
    "hand": "(567m)567t567b111z222z33z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 暗三相逢 for 567m+567t+567b fully concealed, excluding 相逢",
    "hand": "567m567t567b111z222z33z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 明四相逢 for 456m456m456t456b (one suit doubled) with a run exposed, excluding the lower tiers AND 般高 (the doubled m-suit pair is also an identical-run pair)",
    "hand": "(456m)456m456t456b111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 暗四相逢 for 456m456m456t456b fully concealed, excluding the lower tiers AND 般高",
    "hand": "456m456m456t456b111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 明五相逢 for 234234m234234t234b (5 runs, 2+2+1) with a run exposed, excluding every lower tier AND 般高 (both doubled suits)",
    "hand": "(234m)234m234t234t234b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 相逢/明三相逢/暗三相逢/明四相逢/暗四相逢/明五相逢/暗五相逢 (same run across suits)",
    "name": "scores 暗五相逢 for 234234234m234t234b (5 runs, 3+1+1) fully concealed, excluding every lower tier AND 般高",
    "hand": "234m234m234m234t234b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 雙姊妹 (2 distinct 相逢 instances)",
    "name": "scores for 123m+123b and 678t+678b (2 distinct instances, no shared meld)",
    "hand": "123m123b678t678b111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 全姊妹 (every meld is part of a 相逢)",
    "name": "scores for 123m123m123t678b678t77z - both 123m copies pair with the shared 123t (2 instances) plus 678t+678b (1 instance) = 3, excluding 雙姊妹",
    "hand": "123m123m123t678b678t77z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 全姊妹 (every meld is part of a 相逢)",
    "name": "scores for 345t345t345b345b345m55z, even though 相逢 itself is excluded by 暗五相逢",
    "hand": "345t345t345b345b345m55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 樓梯 (5 runs, consecutive starting ranks, any suit)",
    "name": "scores for 123t+234b+345t+456m+567m (starts 1-5, suits unrestricted)",
    "hand": "123t234b345t456m567m77z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 樓梯 (5 runs, consecutive starting ranks, any suit)",
    "name": "doesn't score when a triplet/kong is involved",
    "hand": "123m234m345m456m111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 樓梯 (5 runs, consecutive starting ranks, any suit)",
    "name": "breaks down sorted by starting rank, not by declared-first-then-suit hand.melds order",
    "hand": "(456b)567m345t678t789b99m",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 5
      }
    }
  },
  {
    "group": "PATTERNS: 五步高/全碟 (stricter 樓梯: same suit or a fixed rotation)",
    "name": "scores for 234t345m456b567t678m (rotation t,m,b,t,m - positions 4/5 repeat 1/2), excluding 樓梯",
    "hand": "234t345m456b567t678m55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 五步高/全碟 (stricter 樓梯: same suit or a fixed rotation)",
    "name": "doesn't score for 234t345m456b567m678t - position 4 (m) doesn't repeat position 1 (t)",
    "hand": "234t345m456b567m678t55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 五步高/全碟 (stricter 樓梯: same suit or a fixed rotation)",
    "name": "scores when all 5 runs are the same suit, excluding 樓梯",
    "hand": "123m234m345m456m567m22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 三寶 (range restriction + all-simples + suit purity/missing-one-suit)",
    "name": "scores via 缺五 + 斷么 + 清一色, stacking additively with all 3 constituents",
    "hand": "234t234t678t678t678t33t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 三寶 (range restriction + all-simples + suit purity/missing-one-suit)",
    "name": "scores via 缺五 + 斷么 + 缺一門, stacking additively with all 3 constituents",
    "hand": "234t234t678b678b678b33t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 三寶 (range restriction + all-simples + suit purity/missing-one-suit)",
    "name": "doesn't score when 斷么 fails (a terminal is present), even though 缺五 and 清一色 both hold",
    "hand": "123m123m678m678m678m33m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 兩兄弟/小三兄弟/大三兄弟 (same-rank triplet/kong across suits)",
    "name": "scores 兩兄弟 for 555t+555b (2 suits, same rank)",
    "hand": "555t555b123m456m111z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 兩兄弟/小三兄弟/大三兄弟 (same-rank triplet/kong across suits)",
    "name": "scores 小三兄弟 for 33t+333m+3333b (pair at one suit, triplet/kong at the other 2), excluding 兩兄弟",
    "hand": "333m[3333b]456m789t111z33t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 兩兄弟/小三兄弟/大三兄弟 (same-rank triplet/kong across suits)",
    "name": "scores 大三兄弟 for 555m+555t+555b (no pair involved), excluding 兩兄弟",
    "hand": "555m555t555b111z123b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 兩兄弟/小三兄弟/大三兄弟 (same-rank triplet/kong across suits)",
    "name": "still counts a genuinely separate 兩兄弟 pair that 大三兄弟 doesn't claim - 111m111t111b (rank-1 triple) + 777m777b (unrelated pair, different rank)",
    "hand": "111m111t111b777m777b11z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三色連刻/大三色連刻 (consecutive ranks across suits)",
    "name": "scores 小三色連刻 for 33m+444t+555b (pair at one suit, triplets at the other 2, consecutive ranks)",
    "hand": "444t555b678m111z222z33m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三色連刻/大三色連刻 (consecutive ranks across suits)",
    "name": "scores 大三色連刻 for 333t+4444m+555b (no pair involved, consecutive ranks)",
    "hand": "333t[4444m]555b111z678t22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 小三色連刻/大三色連刻 (consecutive ranks across suits)",
    "name": "stacks 3 小三色連刻 instances (sliding the pair-anchored window) and 1 大三色連刻 instance in the same hand",
    "hand": "222m333t44b555m666t777b",
    "ctx": {
      "winningTile": {
        "suit": "b",
        "rank": 4
      }
    }
  },
  {
    "group": "PATTERNS: 小三色連刻/大三色連刻 (consecutive ranks across suits)",
    "name": "breaks 小三色連刻 down sorted by rank, not pair-always-first - declared 4444m/777m, concealed 333b/666b/111z/55t",
    "hand": "(4444m)(777m)333b666b111z55t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗三色步步高 (3 suits, runs increasing by 1)",
    "name": "scores 明三色步步高 for 456t+567m+678b with one run exposed",
    "hand": "(456t)567m678b111z333z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗三色步步高 (3 suits, runs increasing by 1)",
    "name": "scores 暗三色步步高 for 234m+345t+456b fully concealed",
    "hand": "234m345t456b111z333z22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗三色步步高 (3 suits, runs increasing by 1)",
    "name": "stacks 3 instances for 123456m234567t34599b - each shifted by 1 rank, sharing the lone 345b run",
    "hand": "123456m234567t34599b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗三色步步高 (3 suits, runs increasing by 1)",
    "name": "only opens the ONE specific 123m run the claimed tile actually completed, leaving an identical second 123m run (and the 234t+345b+456m instance) genuinely hidden",
    "hand": "123m123m456m234t345b11z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 對碰 (shanpon: dual-pair wait completed into a triplet)",
    "name": "scores when the winning tile completes a triplet from what was a pair - e.g. tenpai on 44m+44t",
    "hand": "444m123b456b789b111z44t",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 4
      }
    }
  },
  {
    "group": "PATTERNS: 對碰 (shanpon: dual-pair wait completed into a triplet)",
    "name": "doesn't score when the winning tile instead completes a run",
    "hand": "444m123b456b789b111z44t",
    "ctx": {
      "winningTile": {
        "suit": "b",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 對碰 (shanpon: dual-pair wait completed into a triplet)",
    "name": "doesn't score when no winning tile is recorded",
    "hand": "444m123b456b789b111z44t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 對碰 (shanpon: dual-pair wait completed into a triplet)",
    "name": "doesn't score off a DECLARED triplet just because the winning tile also happens to match its rank",
    "hand": "(888t)123m456m789t111z22b",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 8
      }
    }
  },
  {
    "group": "PATTERNS: 將眼 (pair is 2, 5, or 8 - not honors)",
    "name": "scores when the pair is 5",
    "hand": "123456789m234t678t55b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 將眼 (pair is 2, 5, or 8 - not honors)",
    "name": "doesn't score when the pair's rank isn't 2, 5, or 8",
    "hand": "123456789m234t678t11b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 將眼 (pair is 2, 5, or 8 - not honors)",
    "name": "doesn't score when the pair is an honor tile, even at rank 2",
    "hand": "123456789m234t678t22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "scores 假獨 for 12334m completed by 2m - looks like 13m waiting on 2m only, even though the true wait was also open to 5m",
    "hand": "123m234m678t111z789b22z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      }
    }
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "scores 獨獨 for a genuine kanchan wait (13m waiting on 2m only, no overlapping alternate reading), excluding 假獨",
    "hand": "123m456m789t111z234b22b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      }
    }
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "neither scores when no winning tile is recorded",
    "hand": "123m234m678t111z789b22z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "scores 獨獨 (not 假獨/對碰) when the winning tile matches a rank in a DECLARED meld too - declared melds must be excluded from the wait computation entirely",
    "hand": "(777t)(888t)(555t)34566789t",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 8
      }
    }
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "scores 假獨 for a genuine 邊張 (penchan/edge) shape - a 1-2-3 run completed by 3, or a 7-8-9 run completed by 7",
    "hand": "123m456m789t111z789b22b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      }
    }
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "scores 假獨 for a genuine 邊張 (penchan/edge) shape - a 1-2-3 run completed by 3, or a 7-8-9 run completed by 7",
    "hand": "789m456m123t111z789b22b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 7
      }
    }
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "doesn't treat a 2-3 waiting on 1 (or an 7-8 waiting on 9) as 邊張 - those are genuine two-sided (兩面) waits, not edge waits",
    "hand": "123m456m789t111z789b22b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 獨獨/假獨 (genuine vs. fake single wait)",
    "name": "scores 假獨 for 單騎 (tanki): the winning tile completes the pair, but the true wait was much wider - e.g. 1112345678999m111z (nine gates) waits on all of 1m-9m, and drawing 2m specifically makes it the pair",
    "hand": "11122345678999m111z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      }
    }
  },
  {
    "group": "PATTERNS: winning tile whose rank sits in two distinct concealed melds (345b and 456b both holding a 4b)",
    "name": "doesn't wrongly credit 假獨 off the OTHER meld's incidental kanchan shape, and picks the higher-scoring 暗三色步步高 reading over 明",
    "hand": "456m234234t345b456b11z",
    "ctx": {
      "winningTile": {
        "suit": "b",
        "rank": 4
      },
      "selfDraw": false
    }
  },
  {
    "group": "PATTERNS: 明絕 (won on a tile already declared 3 times)",
    "name": "scores when the 3 copies are spread across 3 separate declared runs instead of one triplet - a genuine kanchan single wait on the shared rank",
    "hand": "(345m)(456m)(567m)456m789t22z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 5
      }
    }
  },
  {
    "group": "PATTERNS: 明絕 (won on a tile already declared 3 times)",
    "name": "doesn't require the concealed wait to be single - fires standalone even when a second, un-exhausted wait candidate exists",
    "hand": "(333m)(111z)(222z)345m789t44b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      }
    }
  },
  {
    "group": "PATTERNS: 明絕 (won on a tile already declared 3 times)",
    "name": "gets excluded by 絕絕 when the WHOLE multi-way wait is visibly exhausted (even though its own raw condition is still true)",
    "hand": "(333m)(666m)(567m)345m789t11z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      }
    }
  },
  {
    "group": "PATTERNS: 明絕 (won on a tile already declared 3 times)",
    "name": "doesn't score when the winning tile's kind doesn't match any declared meld",
    "hand": "(777t)(888t)(555t)34566789t",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 9
      }
    }
  },
  {
    "group": "PATTERNS: 明絕 (won on a tile already declared 3 times)",
    "name": "doesn't score when no winning tile is recorded",
    "hand": "(777t)(888t)(555t)34566789t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 絕絕 (multi-way wait narrowed to one visible copy)",
    "name": "doesn't score for an ordinary two-sided wait with no declared-meld collision at all",
    "hand": "(111z)(222z)(333z)345m789t44b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      }
    }
  },
  {
    "group": "PATTERNS: 絕絕 (multi-way wait narrowed to one visible copy)",
    "name": "doesn't score for a genuine single wait (獨獨's territory, not this pattern's)",
    "hand": "(333m)(111z)(222z)123m789t44b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 2
      }
    }
  },
  {
    "group": "PATTERNS: 自摸/門清自摸 (self-drawn win)",
    "name": "scores plain 自摸 when a declared meld is present, not 門清自摸",
    "hand": "(111z)123456789m234t22b",
    "ctx": {
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 自摸/門清自摸 (self-drawn win)",
    "name": "scores 門清自摸 when 門前清 holds too, excluding plain 自摸",
    "hand": "123456789m234t678t22b",
    "ctx": {
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 叮/門清叮 (Riichi, plain and while 門前清)",
    "name": "scores plain 叮 (5 tai) when a declared meld is present, not 門清叮",
    "hand": "(111z)123456789m234t22b",
    "ctx": {
      "riichi": "riichi"
    }
  },
  {
    "group": "PATTERNS: 叮/門清叮 (Riichi, plain and while 門前清)",
    "name": "scores 門清叮 (10 tai) when 門前清 holds too, excluding plain 叮",
    "hand": "123456789m234t678t22b",
    "ctx": {
      "riichi": "riichi"
    }
  },
  {
    "group": "PATTERNS: 叮/門清叮 (Riichi, plain and while 門前清)",
    "name": "stacks freely alongside self-draw - purely a declared flag, not derived from the hand's own shape",
    "hand": "123456789m234t678t22b",
    "ctx": {
      "selfDraw": true,
      "riichi": "riichi"
    }
  },
  {
    "group": "PATTERNS: 天叮/地叮 (Riichi's two upgrades)",
    "name": "scores 天叮 (60 tai), excluding 叮, 門清叮, and (unlike 門清叮) 門前清 itself",
    "hand": "123456789m234t678t22b",
    "ctx": {
      "riichi": "heavenly-riichi"
    }
  },
  {
    "group": "PATTERNS: 天叮/地叮 (Riichi's two upgrades)",
    "name": "scores 地叮 (50 tai), excluding 叮, 門清叮, and (unlike 門清叮) 門前清 itself",
    "hand": "123456789m234t678t22b",
    "ctx": {
      "riichi": "earthly-riichi"
    }
  },
  {
    "group": "PATTERNS: 天叮/地叮 (Riichi's two upgrades)",
    "name": "any declared meld blocks both outright - a call contradicts an untouched initial deal",
    "hand": "(111z)123456789m234t22b",
    "ctx": {
      "riichi": "heavenly-riichi"
    }
  },
  {
    "group": "PATTERNS: 天叮/地叮 (Riichi's two upgrades)",
    "name": "any declared meld blocks both outright - a call contradicts an untouched initial deal",
    "hand": "(123t)123456789m678t22b",
    "ctx": {
      "riichi": "earthly-riichi"
    }
  },
  {
    "group": "PATTERNS: 天叮/地叮 (Riichi's two upgrades)",
    "name": "any declared meld blocks both outright - a call contradicts an untouched initial deal",
    "hand": "(1111z)123456789m234t22t",
    "ctx": {
      "riichi": "heavenly-riichi"
    }
  },
  {
    "group": "PATTERNS: 一發/食叮 (stack additively on top of any declared 叮 state)",
    "name": "一發 adds 5 tai on top of plain 叮",
    "hand": "(111z)123456789m234t22b",
    "ctx": {
      "riichi": "riichi",
      "instantWin": true
    }
  },
  {
    "group": "PATTERNS: 一發/食叮 (stack additively on top of any declared 叮 state)",
    "name": "食叮 adds 5 tai on top of plain 叮",
    "hand": "(111z)123456789m234t22b",
    "ctx": {
      "riichi": "riichi",
      "eatRiichi": true
    }
  },
  {
    "group": "PATTERNS: 一發/食叮 (stack additively on top of any declared 叮 state)",
    "name": "both stack together on top of 天叮",
    "hand": "123456789m234t678t22b",
    "ctx": {
      "riichi": "heavenly-riichi",
      "instantWin": true,
      "eatRiichi": true
    }
  },
  {
    "group": "PATTERNS: 一發/食叮 (stack additively on top of any declared 叮 state)",
    "name": "一發 doesn't score when 叮 isn't declared, but 食叮 does - it's independent of 叮 entirely",
    "hand": "(111z)123456789m234t22b",
    "ctx": {
      "instantWin": true,
      "eatRiichi": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "the manual flag alone scores the pattern when the hand's own melds can't prove it",
    "hand": "(111z)(222z)(333z)345m789t44b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      },
      "manualVisibleTripleWin": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "doesn't double-count when the manual flag is set AND the auto-check already proves it",
    "hand": "(777t)(888t)(555t)34566789t",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 8
      },
      "manualVisibleTripleWin": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "same OR-with-auto-detect shape for 絕絕's manual flag",
    "hand": "(111z)(222z)(333z)345m789t44b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      },
      "manualVisibleExhaustedMultiWait": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "blocks 絕絕's manual flag when the hand's own concealed pre-completion wait was only ever a genuine single wait",
    "hand": "(111m)(222m)(333m)(456t)123t11z",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 3
      },
      "manualVisibleExhaustedMultiWait": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "still allows 明絕's manual flag on that same single-wait hand - 明絕 doesn't care about wait count",
    "hand": "(111m)(222m)(333m)(456t)123t11z",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 3
      },
      "manualVisibleTripleWin": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "blocks the manual flag when the winning tile's kind is ALSO sitting elsewhere in this hand's own concealed tiles",
    "hand": "(111z)(222z)(333z)345m789m88b",
    "ctx": {
      "winningTile": {
        "suit": "b",
        "rank": 8
      },
      "manualVisibleTripleWin": true,
      "manualVisibleExhaustedMultiWait": true
    }
  },
  {
    "group": "PATTERNS: 明絕/絕絕 manual override",
    "name": "still allows the manual flag when the winning tile completes a meld instead, with no concealed duplicate",
    "hand": "(111z)(222z)(333z)345m789m88b",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 9
      },
      "manualVisibleTripleWin": true
    }
  },
  {
    "group": "PATTERNS: 十三么 (Thirteen Orphans)",
    "name": "scores 底 + 十三么 only, for all 13 orphan kinds + a doubled pair + one ordinary meld",
    "hand": "112349m19t19b1234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸 (Thirteen Orphans: one kind held all 4 copies)",
    "name": "scores 暗四歸 when the quad kind (7z) is concealed - no winning tile recorded",
    "hand": "19m19t19b1234567z777z1m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸 (Thirteen Orphans: one kind held all 4 copies)",
    "name": "still scores 暗四歸 when the win is self-drawn, even if the winning tile matches the quad",
    "hand": "19m19t19b1234567z777z1m",
    "ctx": {
      "selfDraw": true,
      "winningTile": {
        "suit": "z",
        "rank": 7
      }
    }
  },
  {
    "group": "PATTERNS: 明/暗四歸 (Thirteen Orphans: one kind held all 4 copies)",
    "name": "scores 明四歸 when the winning tile completed the quad and wasn't self-drawn",
    "hand": "19m19t19b1234567z777z1m",
    "ctx": {
      "winningTile": {
        "suit": "z",
        "rank": 7
      }
    }
  },
  {
    "group": "PATTERNS: 明/暗四歸 (Thirteen Orphans: one kind held all 4 copies)",
    "name": "scores 明四歸 for the quad on a numbered tile (9b) too, not just honors",
    "hand": "19m19t19b1234567z999b7z",
    "ctx": {
      "winningTile": {
        "suit": "b",
        "rank": 9
      }
    }
  },
  {
    "group": "PATTERNS: 混帶么/混老頭 (Thirteen Orphans: the ordinary meld's own shape)",
    "name": "scores 混帶么 when the ordinary meld is a run containing a terminal (123m)",
    "hand": "111239m19t19b1234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么/混老頭 (Thirteen Orphans: the ordinary meld's own shape)",
    "name": "scores 混老頭 (excluding 混帶么) when the ordinary meld is a terminal triplet (111m) - also a quad, so 暗四歸 stacks too",
    "hand": "11119m19t19b12345677z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 混帶么/混老頭 (Thirteen Orphans: the ordinary meld's own shape)",
    "name": "doesn't score when the ordinary meld is an unrelated middle-rank triplet (555b)",
    "hand": "119m19t19b555b1234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 十六不搭 (Sixteen Unrelated Tiles)",
    "name": "scores 底 + 十六不搭 only, for all 7 honors + 3 mutually-unrelated ranks per suit + a doubled pair",
    "hand": "147m147t258b11234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 十六不搭 (Sixteen Unrelated Tiles)",
    "name": "also scores 將眼 when the hand's own pair lands on 2, 5, or 8",
    "hand": "147m147t2258b1234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 不搭三相逢 (十六不搭: same 3 ranks across all 3 suits)",
    "name": "scores an extra 20 tai when all 3 suits use the same 3 ranks",
    "hand": "159m159t159b12345677z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 不搭三相逢 (十六不搭: same 3 ranks across all 3 suits)",
    "name": "doesn't score when the pair isn't an honor, even if all 3 suits' ranks still match",
    "hand": "159m159t1559b1234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 不搭雜龍 (十六不搭: ranks span 1-9 across all 3 suits)",
    "name": "scores an extra 20 tai when the 3 suits' ranks jointly cover 1-9 with no overlap",
    "hand": "147m258b369t12344567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 不搭雜龍 (十六不搭: ranks span 1-9 across all 3 suits)",
    "name": "doesn't score when the pair isn't an honor, even if the suits' ranks still jointly span 1-9",
    "hand": "1447m258b369t1234567z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to the special hands too",
    "name": "scores plain 自摸 (not 門清自摸) for a self-drawn 十三么 - these special hands deliberately never get the 門清 upgrade, since they're always concealed by construction anyway (see 門前清's own \\\"trivially true, not meaningful\\\" exclusion)",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to the special hands too",
    "name": "scores plain 自摸 (not 門清自摸) for a self-drawn 十六不搭",
    "hand": "147m147t258b11234567z",
    "ctx": {
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to the special hands too",
    "name": "doesn't score 獨獨 for a 十六不搭 hand with a genuine multi-way wait",
    "hand": "158m147t369b11234567z",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 7
      }
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to the special hands too",
    "name": "scores 假獨 for a 十三么 hand where the winning tile doubles as both the ordinary meld's edge and its own single",
    "hand": "19m1t7899t19b12345677z",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 9
      }
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to the special hands too",
    "name": "doesn't score 假獨 for the same 十三么 shape when won on the other edge (6t)",
    "hand": "19m1t6789t19b12345677z",
    "ctx": {
      "winningTile": {
        "suit": "t",
        "rank": 6
      }
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores plain 叮 (not 門清叮) for a 十三么 hand - these special hands deliberately never get the 門清 upgrade, same reasoning as 自摸/門清自摸 above; 天叮/地叮 have no concealed-only upgrade of their own, so those apply as-is",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "riichi": "riichi"
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores plain 叮 (not 門清叮) for a 十三么 hand - these special hands deliberately never get the 門清 upgrade, same reasoning as 自摸/門清自摸 above; 天叮/地叮 have no concealed-only upgrade of their own, so those apply as-is",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "riichi": "heavenly-riichi"
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores plain 叮 (not 門清叮) for a 十三么 hand - these special hands deliberately never get the 門清 upgrade, same reasoning as 自摸/門清自摸 above; 天叮/地叮 have no concealed-only upgrade of their own, so those apply as-is",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "riichi": "earthly-riichi"
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores plain 叮 (not 門清叮) for a 十六不搭 hand too",
    "hand": "147m147t258b11234567z",
    "ctx": {
      "riichi": "riichi"
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 一發/食叮 stacking on top of plain 叮 for a 十三么 hand",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "riichi": "riichi",
      "instantWin": true,
      "eatRiichi": true
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 四子內/雙響/天胡 for a 十六不搭 hand",
    "hand": "147m147t258b11234567z",
    "ctx": {
      "earlyWin": "four",
      "multiWin": "double",
      "heavenlyWin": "heaven"
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 七子內/三響/地胡 for a 嚦咕嚦咕 hand",
    "hand": "1111m223344m5566777t",
    "ctx": {
      "earlyWin": "seven",
      "multiWin": "triple",
      "heavenlyWin": "earth"
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 莊 for all 3 special hands",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "dealerStreak": 2
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 莊 for all 3 special hands",
    "hand": "147m147t258b11234567z",
    "ctx": {
      "dealerStreak": 3
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 莊 for all 3 special hands",
    "hand": "1111m223344m5566777t",
    "ctx": {
      "dealerStreak": 1
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 明絕 for 十三么/十六不搭 via the manual override - auto-detect is structurally always false here since these hands always have zero declared melds",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      },
      "manualVisibleTripleWin": true
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "scores 明絕 for 十三么/十六不搭 via the manual override - auto-detect is structurally always false here since these hands always have zero declared melds",
    "hand": "147m147t258b11234567z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      },
      "manualVisibleTripleWin": true
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "blocks 絕絕's manual override for all 3 special hands, for two different reasons",
    "hand": "112349m19t19b1234567z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 3
      },
      "manualVisibleExhaustedMultiWait": true
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "blocks 絕絕's manual override for all 3 special hands, for two different reasons",
    "hand": "147m147t258b11234567z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      },
      "manualVisibleExhaustedMultiWait": true
    }
  },
  {
    "group": "PATTERNS: every purely-declared button pattern applies to the special hands too",
    "name": "blocks 絕絕's manual override for all 3 special hands, for two different reasons",
    "hand": "1111m223344m5566777t",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      },
      "manualVisibleTripleWin": true,
      "manualVisibleExhaustedMultiWait": true
    }
  },
  {
    "group": "PATTERNS: 嚦咕嚦咕/嚦咕嚦咕八飛 (Eight Pairs)",
    "name": "scores 底 + 嚦咕嚦咕 (50) when the pre-completion wait count is 2 or fewer",
    "hand": "1111m223344m5566777t",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 嚦咕嚦咕/嚦咕嚦咕八飛 (Eight Pairs)",
    "name": "scores 底 + 嚦咕嚦咕 (50) for a genuine single wait too",
    "hand": "11223344t778899m777z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 9
      }
    }
  },
  {
    "group": "PATTERNS: 嚦咕嚦咕/嚦咕嚦咕八飛 (Eight Pairs)",
    "name": "scores 底 + 嚦咕嚦咕八飛 (60) when the pre-completion hand is all-even (a clean 8-pairs shape)",
    "hand": "5555t7777t9999m111z77z",
    "ctx": {
      "winningTile": {
        "suit": "z",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 嚦咕嚦咕/嚦咕嚦咕八飛 (Eight Pairs)",
    "name": "falls back to the base 50 tai when no winning tile is recorded",
    "hand": "1111m223344m5566777t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸 applies within 嚦咕嚦咕 too",
    "name": "scores 明四歸 when the winning tile completed a 4-copy kind, claimed",
    "hand": "11112233445566m777z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 明/暗四歸 applies within 嚦咕嚦咕 too",
    "name": "scores 暗四歸 for the same shape when concealed",
    "hand": "11112233445566m777z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 明/暗四歸 applies within 嚦咕嚦咕 too",
    "name": "stacks both 明四歸 and 暗四歸 at once when the hand holds two separate quads",
    "hand": "1111m223344m5555t777z",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 明/暗四歸 applies within 嚦咕嚦咕 too",
    "name": "stacks 暗四歸 across three simultaneous quads",
    "hand": "1111m5555t9999b22z777z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 小五門齊 when all 5 categories are touched, without needing a dedicated meld per category",
    "hand": "1199m1199t1199b11z555z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 斷么 when every tile is ranked 2-8 with no honors",
    "hand": "223344556677m22t888t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 缺一門 when only 2 numbered suits are used and no honors are present",
    "hand": "11223344m556677t888t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 缺五 when no tile is ranked 5 and no honors are present",
    "hand": "1144m2266999t338877b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 大於五 (excluding 缺五) when every tile is ranked 6-9",
    "hand": "66778899m667788999t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 小於五 (excluding 缺五) when every tile is ranked 1-4",
    "hand": "11223344m112233444t",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 三寶 (stacking with its constituents) when 缺五 + 斷么 + 清一色 all hold at once",
    "hand": "22223333446677888m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 混帶X when every non-honor pair/quad group shares a rank with the pair - reuses commonRankAcrossNonHonorMelds as-is",
    "hand": "2222m2222t2222b11122z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "doesn't score 混帶X for a 嚦咕嚦咕 hand with no shared rank across its non-honor groups",
    "hand": "1122m3344t5566b11122z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 三元嚦咕 when all 3 dragon kinds are merely present - no triplet or pair-role required",
    "hand": "112233m22333t556677z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 三風嚦咕 when at least 3 wind kinds are present",
    "hand": "11223344555m112233z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 四喜嚦咕 (excluding 三風嚦咕) when all 4 wind kinds are present",
    "hand": "112233444m11223344z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 清老頭 (excluding 混老頭) for an all-terminals hand",
    "hand": "11119999m1199t11999b",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 混老頭 for a mixed terminals-and-honors hand",
    "hand": "11119999m1199t11b111z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 混一色 (excluding nothing extra) for one numbered suit plus honors",
    "hand": "1122334455m1122333z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 清一色 for a single pure numbered suit",
    "hand": "11223344556677888m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: other patterns reused within 嚦咕嚦咕 (per the user's own list)",
    "name": "scores 字一色 for an all-honors hand, excluding 混老頭 (which needs at least one terminal)",
    "hand": "11112233445566777z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 將眼 stacks per qualifying pair in 嚦咕嚦咕 (not just one)",
    "name": "fires once per pair/quad at rank 2, 5, or 8 - 3 times here for 6 tai total",
    "hand": "2255m88t11224447766z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 將眼 stacks per qualifying pair in 嚦咕嚦咕 (not just one)",
    "name": "doesn't count a quad's extra pair-unit if its rank isn't 2/5/8",
    "hand": "1111m3344667799t111z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 無花/正花/爛花/無字/無字花 apply to 嚦咕嚦咕 too",
    "name": "scores 無字花 (not just 無花) for an honor-free 嚦咕嚦咕 hand with no bonus tiles",
    "hand": "11223344556677m888m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 無花/正花/爛花/無字/無字花 apply to 嚦咕嚦咕 too",
    "name": "scores plain 無花 (not 無字花) when honors are present, even with no bonus tiles",
    "hand": "112233445566m11z777z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to 嚦咕嚦咕 too",
    "name": "scores plain 自摸 (not 門清自摸) for a self-drawn 嚦咕嚦咕 - deliberately never gets the 門清 upgrade, same reasoning as 十三么/十六不搭",
    "hand": "1111m223344m5566777t",
    "ctx": {
      "selfDraw": true
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to 嚦咕嚦咕 too",
    "name": "scores 獨獨 when the pre-completion 嚦咕嚦咕 wait was genuinely single",
    "hand": "112233445566z777z99m",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 9
      }
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to 嚦咕嚦咕 too",
    "name": "scores 假獨 for a 嚦咕嚦咕 hand with two already-tripled kinds - drawing the 4th of either quads it while the other stays a plain triple",
    "hand": "225577t8844222b2b111m",
    "ctx": {
      "winningTile": {
        "suit": "b",
        "rank": 2
      }
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to 嚦咕嚦咕 too",
    "name": "scores 假獨 for a 嚦咕嚦咕 hand with two already-tripled kinds - drawing the 4th of either quads it while the other stays a plain triple",
    "hand": "225577t8844222b111m1m",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to 嚦咕嚦咕 too",
    "name": "doesn't score 假獨 for the same dual-already-tripled shape without a 食胡 tile set",
    "hand": "225577t8844222b2b111m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 自摸/獨獨 apply to 嚦咕嚦咕 too",
    "name": "doesn't score 假獨 for a clean 嚦咕嚦咕 completion (8 pairs, one cleanly upgraded to a triple)",
    "hand": "1122334455667788m1m",
    "ctx": {
      "winningTile": {
        "suit": "m",
        "rank": 1
      }
    }
  },
  {
    "group": "PATTERNS: 嚦咕雙食 (same tiles valid as both 嚦咕嚦咕 and an ordinary hand)",
    "name": "sums both readings' totals and exposes both as `matched`/`second`",
    "hand": "112233m667788t777z55z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "十三么: a dragon triplet picks up 三元牌, the seat wind 正位風, another wind 爛位風",
    "hand": "119m19t19b1234567z777z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "十三么: a dragon triplet picks up 三元牌, the seat wind 正位風, another wind 爛位風",
    "hand": "119m19t19b1234567z111z",
    "ctx": {
      "seatWind": 1
    }
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "十三么: a dragon triplet picks up 三元牌, the seat wind 正位風, another wind 爛位風",
    "hand": "119m19t19b1234567z222z",
    "ctx": {
      "seatWind": 1
    }
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "十三么: the 12 single-tile placeholders never count as honor melds of their own, and a non-honor meld earns nothing",
    "hand": "119m19t19b1234567z123m",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "嚦咕嚦咕: the tripled kind earns it too when it's honors, but not the plain pairs/quads",
    "hand": "2222m2222t2222b55566z",
    "ctx": {}
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "嚦咕嚦咕: the tripled kind earns it too when it's honors, but not the plain pairs/quads",
    "hand": "2222m2222t2222b11122z",
    "ctx": {
      "seatWind": 1
    }
  },
  {
    "group": "PATTERNS: 十三么/嚦咕嚦咕's 3-tile group, when honors, earns 2 tai like any honor meld",
    "name": "嚦咕嚦咕: the tripled kind earns it too when it's honors, but not the plain pairs/quads",
    "hand": "2222m2222t2222b33322z",
    "ctx": {
      "seatWind": 1
    }
  },
  {
    "group": "PATTERNS: honor-meld breakdowns in 十三么/嚦咕嚦咕 show only the group that scored",
    "name": "嚦咕嚦咕: 正位風 lists just the tripled 1z, not the honor quads",
    "hand": "2222z3333z4444z111z22m",
    "ctx": {
      "seatWind": 1
    }
  },
  {
    "group": "PATTERNS: honor-meld breakdowns in 十三么/嚦咕嚦咕 show only the group that scored",
    "name": "嚦咕嚦咕: 三元牌 lists just the tripled dragon, not a dragon quad or pair",
    "hand": "6666z2222m3333t555z77b",
    "ctx": {}
  }
];
